export const horoscopeParts = {
	actions: [
		"for love and romance",
		"for creativity and self-expression",
		"for adventure and excitement",
		"for relaxation and self-care",
		"for learning and growth",
		"for giving back",
		"for forgiveness",
		"for gratitude",
		"to start fresh",
		"to take risks",
		"to be bold",
		"to be kind",
		"to be happy",
		"to be loved",
		"to love",
		"to be yourself",
		"to shine",
		"to dream",
		"to believe",
		"to achieve",
		"to be great",
		"to be positive",
		"to be patient",
		"to be persistent",
		"to be humble",
		"to be open-minded",
		"to be forgiving",
		"to be grateful",
		"to be kind",
		"to be loving",
		"to be compassionate",
		"to be courageous",
		"to be strong",
		"to be beautiful",
		"for success",
		"for health and wellness",
		"for financial abundance",
		"for good luck",
		"for peace and harmony",
		"for joy and happiness",
		"for love and light",
	],

	actionObjects: [
		"Today is a great day",
		"Today is a good day",
		"Today is a bad day",
		"Today is a terrible day",
		"Today is a wonderful day",
		"Today is a beautiful day",
		"Today is a magical day",
	],

	predictions: [
		"have a great day today!",
		"learn something new today!",
		"meet someone new today!",
		"make a difference in someone's life today!",
		"achieve your goals today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
		"be happy today!",
		"be loved today!",
		"be successful today!",
		"be healthy today!",
		"be wealthy today!",
		"be lucky today!",
		"be at peace today!",
	],
	predictionObjects: [
		"You are going to",
		"You will",
		"You should",
		"You must",
		"You can",
		"You could",
		"You might",
		"You may",
		"You certainly will",
		"You definitely will",
		"You will definitely",
		"You will certainly",
		"You will probably",
	],
};
